# Generated by Django 3.2.7 on 2021-09-28 15:54

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='номер рейса')),
                ('duration', models.DurationField(validators=[django.core.validators.MinValueValidator(datetime.timedelta(seconds=60))], verbose_name='длительность')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='стоимость')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arriving_flights', related_query_name='arriving_flight', to='cities.city', verbose_name='город назначения')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departing_flights', related_query_name='departing_flight', to='cities.city', verbose_name='город отправления')),
            ],
            options={
                'verbose_name': 'рейс',
                'verbose_name_plural': 'рейсы',
            },
        ),
        migrations.AddConstraint(
            model_name='flight',
            constraint=models.UniqueConstraint(fields=('origin', 'destination', 'duration', 'price'), name='origin_destination_duration_price_unique'),
        ),
        migrations.AddConstraint(
            model_name='flight',
            constraint=models.CheckConstraint(check=models.Q(('origin', django.db.models.expressions.F('destination')), _negated=True), name='origin_ne_destination'),
        ),
        migrations.AddConstraint(
            model_name='flight',
            constraint=models.CheckConstraint(check=models.Q(('duration__gt', datetime.timedelta(seconds=60))), name='duration_gt_1_minute'),
        ),
        migrations.AddConstraint(
            model_name='flight',
            constraint=models.CheckConstraint(check=models.Q(('price__gt', Decimal('0'))), name='price_gt_0'),
        ),
    ]
