# Generated by Django 3.2.7 on 2021-09-29 10:36

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название маршрута')),
                ('duration', models.DurationField(verbose_name='длительность')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='стоимость')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arriving_routes', related_query_name='arriving_route', to='cities.city', verbose_name='город назначения')),
                ('flights', models.ManyToManyField(to='flights.Flight', verbose_name='рейсы')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departing_routes', related_query_name='departing_route', to='cities.city', verbose_name='город отправления')),
            ],
            options={
                'verbose_name': 'маршрут',
                'verbose_name_plural': 'маршруты',
            },
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('origin', 'destination', 'duration', 'price'), name='route_origin_destination_duration_price_unique'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.CheckConstraint(check=models.Q(('origin', django.db.models.expressions.F('destination')), _negated=True), name='route_origin_ne_destination'),
        ),
    ]
