# Generated by Django 3.2.7 on 2021-10-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='duration',
            field=models.DurationField(verbose_name='время в пути'),
        ),
    ]
